### ISSUE TITLE
Using textareas instead of input fields

### ISSUE THREAD

**Issue by iteles** [dwyl/autoform#23]
For fields in my form which require more details and therefore longer inputs from my users, 
I would like to have the option to use a `textarea` instead of the default input field,
In order to improve the user experience, allowing users to see more of what they have typed.

**Comment by RobStallion** [comment]
@iteles I was planning on trying to build in that functionality. I actually just spoke to @Cleop about it this afternoon and was planning on opening this issue (but you beat me to it 👍 )

**Comment by nelsonic** [comment]
Hi @RobStallion, what is the _field_ that you are rendering that _should_ be a **`textarea`**?
Could you please open an issue in https://github.com/dwyl/fields/issues describing the field?
Based on the field definition which is used in the Schema, 
**`autoform`** should know how to render the appropriate UI. (_in this case a  **`textarea`**_)
We _must_ get into the habit of defining _re-useable_ semantic fields so that we can build Apps _faster_.
Not "lockup" all functionality in the client application. 
Thanks! ✨

**Comment by iteles** [comment]
Moved to https://github.com/dwyl/fields/issues/20
